#include<iostream>
using namespace std; 

// define a own custom exception handle class 

struct MyException: public exception {
    const char * what() const throw (){
       return "MyException:  generated By Amar";
    }
};


int main(){
    
    int x , y; 

    cout << "Enter a variable x and y" << endl;
    cin >> x >> y;

    try {
      if(x == 0 ||  y == 0){
        throw MyException();
      }
      cout << x / y << endl;

    } catch(MyException& e){
       cout << "Error: \n" << endl;
       cout << e.what() << endl;
    } 

    return 0;

}